### ISSUE TITLE
Create a progress dialogue for when tool is running

### ISSUE THREAD

**Issue by amyburness** [kartoza/cplus-plugin#39]
The progress dialog should open once a user has all paths set up and clicks Run. A message should be shown if the processing succeeded, and the same goes for if it failed.

**If the processing succeeded:**
Once the process finishes and the user clicks OK, the resulting rasters should be added. See https://github.com/kartoza/ci-cplus-scoping/issues/42.
For the Report, see https://github.com/kartoza/ci-cplus-scoping/issues/43.

![image](https://user-images.githubusercontent.com/77841514/231763289-ab39d911-27ca-43ed-9a6e-7de5e33ba4e7.png)

**Comment by vermeulendivan** [comment]
**Suggestion:**
Currently the scope states that the user should be restricted to QGIS while the processing is performed in QGIS. Won't it make more sense to run this in a separate thread so that the user can still use QGIS?

![image](https://user-images.githubusercontent.com/79740955/231791239-f4c0ad9e-7a84-44e3-90cd-d2bcac89b4af.png)
